### ISSUE TITLE
fails to resolve node_modules in watch mode -- need to use `rollup-plugin-node-resolve`

### ISSUE THREAD

**Issue by macrozone** [ezolenko/rollup-plugin-typescript2#124]
#### What happens and why it is wrong

if you use rollup in watch mode (`rollup -cw`) it will build the first time, then fail, because it can't resolve some dependencies:

```
Error: Could not load xxx (imported by /path/to/file.ts): ENOENT: no such file or directory, open 'xxx'
```

#### Versions

 "typescript": "^3.2.1",
  "rollup": "^0.67.4",
  "rollup-plugin-typescript2": "^0.18.0",

#### rollup.config.js

```js
import typescript from 'rollup-plugin-typescript2'

export default {
  input: './src/index.ts',
  plugins: [typescript()],
  output: [
    {
      file: 'dist/index.js',
      format: 'cjs'
    }
  ]
}

```

#### tsconfig.json

```json5
{
  "compilerOptions": {
    "module": "ESNext",
    "esModuleInterop": true,
    "target": "es6",
    "noImplicitAny": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist",

    "baseUrl": ".",
    "resolveJsonModule": true,
    "paths": {
      "*": ["node_modules/*", "src/types/*"]
    }
  },
  "include": ["src/**/*", "package.json"]
}
```

#### plugin output with verbosity 3

sorry, output way too big

**Comment by ezolenko** [comment]
@macrozone I just released 0.18.1 with a watch related fix, could you try that?

**Comment by macrozone** [comment]
@ezolenko wow that was fast!

i tried it, but i still have the same error :-/

**Comment by ezolenko** [comment]
That was in the works for a while for #32 :)

Could you make a small repo with reproduction or at least post the full plugin output with verbosity 3? (you can put it under the fold)

**Comment by agilgur5** [comment]
Looking at the Rollup config here, I believe the issue may be that [`@rollup/plugin-node-resolve`](https://github.com/rollup/plugins/tree/master/packages/node-resolve) (formerly `rollup-plugin-node-resolve` when this issue was opened) was not used as a plugin, and that is generally _required_ for reading `node_modules` with _any_ kind of Rollup config.

Closing this out due to the above as well as the fact that issue author has not responded to requests for more info (in a few years in this case).
