### ISSUE TITLE
tslib `DeprecationWarning` with node v16 (15?)

### ISSUE THREAD

**Issue by qmhc** [ezolenko/rollup-plugin-typescript2#267]
#### What happens and why it is wrong

```log
(node:37540) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at E:\pocket\node_modules\rollup-plugin-typescript2\node_modules\tslib\package.json.
Update this package.json to use a subpath pattern like "./*".
```

#### Environment

```
operating system: Windows 10
node: 16.0.0
npm: 7.11.1
yarn: 2.4.1
```

##### Versions

```text
rollup: ^2.41.0
rollup-plugin-typescript2: ^0.30.0
typescript: 4.2.3
```

**Comment by retarsis** [comment]
this is the annoying one 😔

**Comment by originalix** [comment]
I have the same problem.

**Comment by mesqueeb** [comment]
Me too

**Comment by retarsis** [comment]
too

**Comment by pixelass** [comment]
please use the thumbs up on the first comment instead of spamming the thread. New (useless) comments will notify everybody subscribed to this thread.
Thank you. 

<img width="528" alt="Deprecation_Warning_with_node_v16__15___·_Issue__267_·_ezolenko_rollup-plugin-typescript2" src="https://user-images.githubusercontent.com/1148334/127779534-61ae8525-8a75-4c45-aa62-6ee2b1980fb1.png">

**Comment by iomariani** [comment]
This is actually an issue on tslib package:

https://github.com/microsoft/tslib/pull/135

**Comment by ezolenko** [comment]
Should be fixed in 0.31.0

**Comment by leikoilja** [comment]
@ezolenko, I am still seeing the same issue even with `rollup-plugin-typescript2==0.31.1`:
```bash
(node:68636) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at  *****js/node_modules/rollup-plugin-typescript2/node_modules/tslib/package.json.
```

**Comment by ezolenko** [comment]
@leikoilja 
What's your versions in plugin output? This part: 
```
rpt2: typescript version: 4.2.4
rpt2: tslib version: 2.3.1
rpt2: rollup version: 2.48.0
rpt2: rollup-plugin-typescript2 version: 0.31.2```

**Comment by agilgur5** [comment]
Closing as this was a false alarm on the re-opening.

Should be fixed in >=0.31.0 per above
